name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-20.04  

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 2375:2375
        env:
          DOCKER_TLS_CERTDIR: ""
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.7'

      - name: Install dependencies
        run: |  
          python -m pip install --upgrade pip
          pwd
          pip install -r .github/workflows/server_api/requirements.txt

      - name: Build Docker image
        working-directory: server_api
        run: |
          docker build -t toxic-metr-app .

      - name: Run Docker Compose
        working-directory: server_api
        run: |
          docker-compose up --build -d

      - name: Check service health
        run: |
          sleep 10
          curl -f http://localhost:8000 || exit 1

  cleanup:
    runs-on: ubuntu-20.04  
    if: always()

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Stop Docker Compose
        working-directory: ./server_api  
        run: docker-compose down
